# Linux command
alias egr='grep -nr '
alias ls='ls -l'

# Git
alias gad='git add'
alias gbr='git branch'
alias gcl='git clean'
alias gcm='git commit'
alias gco='git checkout'
alias gcp='git cherry-pick'
alias gdf='git diff'
alias gft='git fetch'
alias glg='git log'
alias gmr='git merge'
alias gpl='git pull'
alias gps='git push'
alias grb='git rebase'
alias grboms='git rebase origin/master --ignore-date'
alias grm='git rm'
alias grs='git reset'
alias grv='git revert'
alias gsh='git show'
alias gstash='git stash'
alias gst='git status'
